id: conexco/shopware-bootstrap-theme
name: Bootstrap Theme for Shopware
version: 1.0.0
license: GPL-3.0
licenseUrl: https://www.gnu.org/licenses/gpl-3.0.en.html

# download button
# if download.popup is true, the download button will open a popup with several download options
# otherwise it will simply open download.url and other options are ignored
# if download.popup is true, any option is optional
# download.cdn.img is optional
download:
  popup: false
  url: https://github.com/conexco/shopware-bootstrap-theme/

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: true

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/conexco/shopware-bootstrap-theme

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/conexco/shopware-bootstrap-theme

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
# analytics:
#   account:
#   domain:

# github buttons
githubButton:
  user: conexco
  repo: shopware-bootstrap-theme

# facebook buttons
facebook:
  enabled: true
  profileUrl: https://www.facebook.com/conexco

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
developmentUrl: http://localhost:4000
developmentUrl: "http://localhost:4000"
