# global
id: conexco/shopware-bootstrap-theme
name: Bootstrap Theme for Shopware
description: The Shopware Bootstrap Theme helps you build fast, robust, and adaptable responsive shopware themes. Kick-start your shopware theme with the combined knowledge and effort of 1000s of custom shopware themes.
version: 1.0.3
license: GPL-3.0
licenseUrl: https://www.gnu.org/licenses/gpl-3.0.en.html

# download
download:
    url: https://github.com/conexco/shopware-bootstrap-theme/

# header
header:
    color1: "#080331"
    color2: "#673051"

# google analytics
analytics:
    account: UA-21473902-5
    domain: auto

# github
githubButton:
    user: conexco
    repo: https://github.com/conexco/shopware-bootstrap-theme/

# facebook
facebook:
    enabled: false
    profileUrl: https://www.facebook.com/conexco

# excludes
exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile', 'vendor']

# plugins
plugins:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap

# social
title:                      "Bootstrap for shopware"
description:                "The Shopware Bootstrap Theme helps you build fast, robust, and adaptable responsive shopware themes."
twitter:                    conexco
authors:                    conexco
social_twitter_image_path:  /assets/img/twitter_800x418.png
social_facebook_image_path: /assets/img/facebook_1200x630.png
